spring:
  messages:
    encoding: UTF-8
    basename: messages
    cache-duration: -1

mybatis:
  mapperLocations: classpsth*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdDutImpl
